In [31]:
import pandas as pd

tekme = pd.read_csv('podatki/tekme.csv')
tekme.head()

,datum,domaca_ekipa,goli_domaca,goli_gost,gostujoca_ekipa,rdeci_domaci,rdeci_gostje,rumeni_domaci,rumeni_gostje,strelci_domaci,strelci_gostje
0,17 Aug 2025,Chelsea,0,0,Crystal Palace,0,0,2,3,NaN,NaN
1,16 Aug 2025,Aston Villa,0,0,Newcastle United,1,0,1,1,NaN,NaN
2,16 Aug 2025,Brighton and Hove Albion,1,1,Fulham,0,0,3,3,NaN,Rodrigo Muniz (Forward) 90+6'
3,17 Aug 2025,Manchester United,0,1,Arsenal,0,0,1,4,NaN,Riccardo Calafiori (Defender) 13'
4,18 Aug 2025,Leeds United,1,0,Everton,0,0,0,2,NaN,NaN

In [2]:
len(tekme)

760

In [3]:
tekme.info()

<class 'pandas.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   datum            760 non-null    str
 1   domaca_ekipa     760 non-null    str
 2   goli_domaca      760 non-null    int64
 3   goli_gost        760 non-null    int64
 4   gostujoca_ekipa  760 non-null    str
 5   rdeci_domaci     760 non-null    int64
 6   rdeci_gostje     760 non-null    int64
 7   rumeni_domaci    760 non-null    int64
 8   rumeni_gostje    760 non-null    int64
 9   strelci_domaci   552 non-null    str
 10  strelci_gostje   537 non-null    str
dtypes: int64(6), str(5)
memory usage: 65.4 KB

In [4]:
tekme.describe()

,goli_domaca,goli_gost,rdeci_domaci,rdeci_gostje,rumeni_domaci,rumeni_gostje
count,760.000000,760.000000,760.000000,760.000000,760.000000,760.000000
mean,1.519737,1.322368,0.063158,0.063158,1.832895,2.171053
std,1.224317,1.142092,0.259137,0.243407,1.343396,1.417825
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,1.000000,1.000000,0.000000,0.000000,2.000000,2.000000
75%,2.000000,2.000000,0.000000,0.000000,3.000000,3.000000
max,7.000000,6.000000,2.000000,1.000000,7.000000,8.000000

In [5]:
tekme.isna().sum()

datum                0
domaca_ekipa         0
goli_domaca          0
goli_gost            0
gostujoca_ekipa      0
rdeci_domaci         0
rdeci_gostje         0
rumeni_domaci        0
rumeni_gostje        0
strelci_domaci     208
strelci_gostje     223
dtype: int64

In [6]:
tekme['datum'] = pd.to_datetime(tekme['datum'], format='%d %b %Y')

### 1. Koliko tekem je bilo odigranih v vsaki sezoni

In [8]:
def doloci_sezono(datum):
    if datum.month >= 8:
        sezona = str(datum.year) + '/' + str(datum.year + 1)
    else:
        sezona = str(datum.year - 1) + '/' + str(datum.year)
    return sezona

tekme['sezona'] = tekme['datum'].apply(doloci_sezono)
tekme['sezona'].value_counts()

sezona
2025/2026    380
2024/2025    380
Name: count, dtype: int64

# 1. Analiza tekem glede na gole

### 2. Katera ekipa je dosegla največ golov skupaj?

#### 2.1 Goli - Domači

In [12]:
goli_doma = tekme.groupby('domaca_ekipa')['goli_domaca'].sum()
goli_doma = goli_doma.sort_values(ascending=False)
goli_doma

domaca_ekipa
Manchester City             88
Liverpool                   76
Arsenal                     76
Newcastle United            76
Brentford                   73
Aston Villa                 66
Manchester United           62
Chelsea                     61
Brighton and Hove Albion    60
Fulham                      57
Tottenham Hotspur           57
Everton                     52
AFC Bournemouth             52
West Ham United             50
Wolverhampton Wanderers     46
Nottingham Forest           46
Crystal Palace              43
Leeds United                29
Sunderland                  25
Burnley                     18
Leicester City              15
Ipswich Town                14
Southampton                 13
Name: goli_domaca, dtype: int64

In [ ]:
skupni_goli_domacih = goli_doma.sum()

#### 2.2 Goli - Gostujoči

In [13]:
goli_gost = tekme.groupby('gostujoca_ekipa')['goli_gost'].sum()
goli_gost = goli_gost.sort_values(ascending=False)
goli_gost

gostujoca_ekipa
Liverpool                   73
Arsenal                     64
AFC Bournemouth             64
Manchester City             61
Chelsea                     61
Nottingham Forest           60
Brighton and Hove Albion    58
Tottenham Hotspur           55
Manchester United           51
Crystal Palace              49
Aston Villa                 48
Brentford                   48
Newcastle United            45
Fulham                      44
West Ham United             42
Everton                     37
Wolverhampton Wanderers     35
Ipswich Town                22
Burnley                     20
Leeds United                20
Leicester City              18
Sunderland                  17
Southampton                 13
Name: goli_gost, dtype: int64

#### 2.3 Goli - Skupno

In [17]:
goli_skupaj = goli_doma.add(goli_gost, fill_value=0)
goli_skupaj = goli_skupaj.sort_values(ascending=False)
goli_skupaj.index.name = 'ekipa'
goli_skupaj.head(10)

ekipa
Liverpool                   149
Manchester City             149
Arsenal                     140
Chelsea                     122
Newcastle United            121
Brentford                   121
Brighton and Hove Albion    118
AFC Bournemouth             116
Aston Villa                 114
Manchester United           113
dtype: int64

## 3. Ali ima domača ekipa prednost glede na število golov?

In [19]:
povp_doma = tekme.groupby('domaca_ekipa')['goli_domaca'].mean()
povp_doma = povp_doma.sort_values(ascending=False)
povp_doma

domaca_ekipa
Manchester City             2.315789
Liverpool                   2.000000
Arsenal                     2.000000
Newcastle United            2.000000
Brentford                   1.921053
Aston Villa                 1.736842
Manchester United           1.631579
Chelsea                     1.605263
Brighton and Hove Albion    1.578947
Leeds United                1.526316
Tottenham Hotspur           1.500000
Fulham                      1.500000
AFC Bournemouth             1.368421
Everton                     1.368421
West Ham United             1.315789
Sunderland                  1.315789
Wolverhampton Wanderers     1.210526
Nottingham Forest           1.210526
Crystal Palace              1.131579
Burnley                     0.947368
Leicester City              0.789474
Ipswich Town                0.736842
Southampton                 0.684211
Name: goli_domaca, dtype: float64

In [20]:
povp_gost = tekme.groupby('gostujoca_ekipa')['goli_gost'].mean()
povp_gost = povp_gost.sort_values(ascending=False)
povp_gost

gostujoca_ekipa
Liverpool                   1.921053
Arsenal                     1.684211
AFC Bournemouth             1.684211
Manchester City             1.605263
Chelsea                     1.605263
Nottingham Forest           1.578947
Brighton and Hove Albion    1.526316
Tottenham Hotspur           1.447368
Manchester United           1.342105
Crystal Palace              1.289474
Aston Villa                 1.263158
Brentford                   1.263158
Newcastle United            1.184211
Ipswich Town                1.157895
Fulham                      1.157895
West Ham United             1.105263
Burnley                     1.052632
Leeds United                1.052632
Everton                     0.973684
Leicester City              0.947368
Wolverhampton Wanderers     0.921053
Sunderland                  0.894737
Southampton                 0.684211
Name: goli_gost, dtype: float64

In [30]:
izidi = []

for i in range(len(tekme)):
    doma_goli = tekme['goli_domaca'].iloc[i]
    gost_goli = tekme['goli_gost'].iloc[i]
    
    if doma_goli > gost_goli:
        izid = 'Zmaga domačih'
    elif doma_goli < gost_goli:
        izid = 'Zmaga gostov'
    else:
        izid = 'Neodločeno'
    
    izidi.append(izid)


stevilo = tekme['izid'].value_counts()
delez = tekme['izid'].value_counts(normalize=True) * 100

povzetek = pd.DataFrame({
    'število': stevilo,
    'delež (%)': delez.round(1)
})

povzetek

               število  delež (%)
izid
Zmaga domačih      317       41.7
Zmaga gostov       246       32.4
Neodločeno         197       25.9

## 4. Delež vseh zadetkov glede na pozicijo igralca

In [32]:
import re

vse_pozicije = []

for besedilo in tekme['strelci_domaci'].dropna():
    vse_pozicije += re.findall(r'\(([A-Za-z/ ]+)\)', besedilo)

for besedilo in tekme['strelci_gostje'].dropna():
    vse_pozicije += re.findall(r'\(([A-Za-z/ ]+)\)', besedilo)

len(vse_pozicije)

pozicije_stevilo = pd.Series(vse_pozicije).value_counts()
pozicije_delez = pd.Series(vse_pozicije).value_counts(normalize=True) * 100

povzetek_pozicij = pd.DataFrame({
    'stevilo_golov': pozicije_stevilo,
    'delez (%)': pozicije_delez.round(1)
})

povzetek_pozicij

                     stevilo_golov  delez (%)
Midfielder/Forward             621       37.8
Forward                        443       27.0
Midfielder                     281       17.1
Defender/Midfielder            173       10.5
Defender                       123        7.5

## 5. V katerem delu igre so najbolj pogosti goli?

In [36]:
vse_minute = []

for besedilo in tekme['strelci_domaci'].dropna():
    vse_minute += re.findall(r"(\d{1,3})(?:\+\d{1,2})?'", besedilo)

for besedilo in tekme['strelci_gostje'].dropna():
    vse_minute += re.findall(r"(\d{1,3})(?:\+\d{1,2})?'", besedilo)

vse_minute = [int(m) for m in vse_minute]
len(vse_minute)

intervali = [0, 15, 30, 45, 60, 75, 91]
oznake = ['0-15', '16-30', '31-45', '46-60', '61-75', '76-90+']

minute_kategorije = pd.cut(vse_minute, bins=intervali, labels=oznake, right=True)
minute_kategorije.value_counts().sort_index()

0-15      254
16-30     254
31-45     370
46-60     304
61-75     298
76-90+    461
Name: count, dtype: int64

v katerem delu igre je največ rdečih/ rumenih kartonov?